// SPDX-License-Identifier: MIT

namespace SDL.Events
{
    public enum KeyCode
    {
        SDLK_UNKNOWN = 0,

        SDLK_RETURN = '\r',
        SDLK_ESCAPE = 27,
        SDLK_BACKSPACE = '\b',
        SDLK_TAB = '\t',
        SDLK_SPACE = ' ',
        SDLK_EXCLAIM = '!',
        SDLK_QUOTEDBL = '"',
        SDLK_HASH = '#',
        SDLK_PERCENT = '%',
        SDLK_DOLLAR = '$',
        SDLK_AMPERSAND = '&',
        SDLK_QUOTE = '\'',
        SDLK_LEFTPAREN = '(',
        SDLK_RIGHTPAREN = ')',
        SDLK_ASTERISK = '*',
        SDLK_PLUS = '+',
        SDLK_COMMA = ',',
        SDLK_MINUS = '-',
        SDLK_PERIOD = '.',
        SDLK_SLASH = '/',
        SDLK_0 = '0',
        SDLK_1 = '1',
        SDLK_2 = '2',
        SDLK_3 = '3',
        SDLK_4 = '4',
        SDLK_5 = '5',
        SDLK_6 = '6',
        SDLK_7 = '7',
        SDLK_8 = '8',
        SDLK_9 = '9',
        SDLK_COLON = ':',
        SDLK_SEMICOLON = ';',
        SDLK_LESS = '<',
        SDLK_EQUALS = '=',
        SDLK_GREATER = '>',
        SDLK_QUESTION = '?',
        SDLK_AT = '@',
        /*
        Skip uppercase letters
        */
        SDLK_LEFTBRACKET = '[',
        SDLK_BACKSLASH = '\\',
        SDLK_RIGHTBRACKET = ']',
        SDLK_CARET = '^',
        SDLK_UNDERSCORE = '_',
        SDLK_BACKQUOTE = '`',
        SDLK_a = 'a',
        SDLK_b = 'b',
        SDLK_c = 'c',
        SDLK_d = 'd',
        SDLK_e = 'e',
        SDLK_f = 'f',
        SDLK_g = 'g',
        SDLK_h = 'h',
        SDLK_i = 'i',
        SDLK_j = 'j',
        SDLK_k = 'k',
        SDLK_l = 'l',
        SDLK_m = 'm',
        SDLK_n = 'n',
        SDLK_o = 'o',
        SDLK_p = 'p',
        SDLK_q = 'q',
        SDLK_r = 'r',
        SDLK_s = 's',
        SDLK_t = 't',
        SDLK_u = 'u',
        SDLK_v = 'v',
        SDLK_w = 'w',
        SDLK_x = 'x',
        SDLK_y = 'y',
        SDLK_z = 'z',

        SDLK_CAPSLOCK = ScanCode.SDL_SCANCODE_CAPSLOCK | ScanCode.MASK,

        SDLK_F1 = ScanCode.SDL_SCANCODE_F1 | ScanCode.MASK,
        SDLK_F2 = ScanCode.SDL_SCANCODE_F2 | ScanCode.MASK,
        SDLK_F3 = ScanCode.SDL_SCANCODE_F3 | ScanCode.MASK,
        SDLK_F4 = ScanCode.SDL_SCANCODE_F4 | ScanCode.MASK,
        SDLK_F5 = ScanCode.SDL_SCANCODE_F5 | ScanCode.MASK,
        SDLK_F6 = ScanCode.SDL_SCANCODE_F6 | ScanCode.MASK,
        SDLK_F7 = ScanCode.SDL_SCANCODE_F7 | ScanCode.MASK,
        SDLK_F8 = ScanCode.SDL_SCANCODE_F8 | ScanCode.MASK,
        SDLK_F9 = ScanCode.SDL_SCANCODE_F9 | ScanCode.MASK,
        SDLK_F10 = ScanCode.SDL_SCANCODE_F10 | ScanCode.MASK,
        SDLK_F11 = ScanCode.SDL_SCANCODE_F11 | ScanCode.MASK,
        SDLK_F12 = ScanCode.SDL_SCANCODE_F12 | ScanCode.MASK,

        SDLK_PRINTSCREEN = ScanCode.SDL_SCANCODE_PRINTSCREEN | ScanCode.MASK,
        SDLK_SCROLLLOCK = ScanCode.SDL_SCANCODE_SCROLLLOCK | ScanCode.MASK,
        SDLK_PAUSE = ScanCode.SDL_SCANCODE_PAUSE | ScanCode.MASK,
        SDLK_INSERT = ScanCode.SDL_SCANCODE_INSERT | ScanCode.MASK,
        SDLK_HOME = ScanCode.SDL_SCANCODE_HOME | ScanCode.MASK,
        SDLK_PAGEUP = ScanCode.SDL_SCANCODE_PAGEUP | ScanCode.MASK,
        SDLK_DELETE = 127,
        SDLK_END = ScanCode.SDL_SCANCODE_END | ScanCode.MASK,
        SDLK_PAGEDOWN = ScanCode.SDL_SCANCODE_PAGEDOWN | ScanCode.MASK,
        SDLK_RIGHT = ScanCode.SDL_SCANCODE_RIGHT | ScanCode.MASK,
        SDLK_LEFT = ScanCode.SDL_SCANCODE_LEFT | ScanCode.MASK,
        SDLK_DOWN = ScanCode.SDL_SCANCODE_DOWN | ScanCode.MASK,
        SDLK_UP = ScanCode.SDL_SCANCODE_UP | ScanCode.MASK,

        SDLK_NUMLOCKCLEAR = ScanCode.SDL_SCANCODE_NUMLOCKCLEAR | ScanCode.MASK,
        SDLK_KP_DIVIDE = ScanCode.SDL_SCANCODE_KP_DIVIDE | ScanCode.MASK,
        SDLK_KP_MULTIPLY = ScanCode.SDL_SCANCODE_KP_MULTIPLY | ScanCode.MASK,
        SDLK_KP_MINUS = ScanCode.SDL_SCANCODE_KP_MINUS | ScanCode.MASK,
        SDLK_KP_PLUS = ScanCode.SDL_SCANCODE_KP_PLUS | ScanCode.MASK,
        SDLK_KP_ENTER = ScanCode.SDL_SCANCODE_KP_ENTER | ScanCode.MASK,
        SDLK_KP_1 = ScanCode.SDL_SCANCODE_KP_1 | ScanCode.MASK,
        SDLK_KP_2 = ScanCode.SDL_SCANCODE_KP_2 | ScanCode.MASK,
        SDLK_KP_3 = ScanCode.SDL_SCANCODE_KP_3 | ScanCode.MASK,
        SDLK_KP_4 = ScanCode.SDL_SCANCODE_KP_4 | ScanCode.MASK,
        SDLK_KP_5 = ScanCode.SDL_SCANCODE_KP_5 | ScanCode.MASK,
        SDLK_KP_6 = ScanCode.SDL_SCANCODE_KP_6 | ScanCode.MASK,
        SDLK_KP_7 = ScanCode.SDL_SCANCODE_KP_7 | ScanCode.MASK,
        SDLK_KP_8 = ScanCode.SDL_SCANCODE_KP_8 | ScanCode.MASK,
        SDLK_KP_9 = ScanCode.SDL_SCANCODE_KP_9 | ScanCode.MASK,
        SDLK_KP_0 = ScanCode.SDL_SCANCODE_KP_0 | ScanCode.MASK,
        SDLK_KP_PERIOD = ScanCode.SDL_SCANCODE_KP_PERIOD | ScanCode.MASK,

        SDLK_APPLICATION = ScanCode.SDL_SCANCODE_APPLICATION | ScanCode.MASK,
        SDLK_POWER = ScanCode.SDL_SCANCODE_POWER | ScanCode.MASK,
        SDLK_KP_EQUALS = ScanCode.SDL_SCANCODE_KP_EQUALS | ScanCode.MASK,
        SDLK_F13 = ScanCode.SDL_SCANCODE_F13 | ScanCode.MASK,
        SDLK_F14 = ScanCode.SDL_SCANCODE_F14 | ScanCode.MASK,
        SDLK_F15 = ScanCode.SDL_SCANCODE_F15 | ScanCode.MASK,
        SDLK_F16 = ScanCode.SDL_SCANCODE_F16 | ScanCode.MASK,
        SDLK_F17 = ScanCode.SDL_SCANCODE_F17 | ScanCode.MASK,
        SDLK_F18 = ScanCode.SDL_SCANCODE_F18 | ScanCode.MASK,
        SDLK_F19 = ScanCode.SDL_SCANCODE_F19 | ScanCode.MASK,
        SDLK_F20 = ScanCode.SDL_SCANCODE_F20 | ScanCode.MASK,
        SDLK_F21 = ScanCode.SDL_SCANCODE_F21 | ScanCode.MASK,
        SDLK_F22 = ScanCode.SDL_SCANCODE_F22 | ScanCode.MASK,
        SDLK_F23 = ScanCode.SDL_SCANCODE_F23 | ScanCode.MASK,
        SDLK_F24 = ScanCode.SDL_SCANCODE_F24 | ScanCode.MASK,
        SDLK_EXECUTE = ScanCode.SDL_SCANCODE_EXECUTE | ScanCode.MASK,
        SDLK_HELP = ScanCode.SDL_SCANCODE_HELP | ScanCode.MASK,
        SDLK_MENU = ScanCode.SDL_SCANCODE_MENU | ScanCode.MASK,
        SDLK_SELECT = ScanCode.SDL_SCANCODE_SELECT | ScanCode.MASK,
        SDLK_STOP = ScanCode.SDL_SCANCODE_STOP | ScanCode.MASK,
        SDLK_AGAIN = ScanCode.SDL_SCANCODE_AGAIN | ScanCode.MASK,
        SDLK_UNDO = ScanCode.SDL_SCANCODE_UNDO | ScanCode.MASK,
        SDLK_CUT = ScanCode.SDL_SCANCODE_CUT | ScanCode.MASK,
        SDLK_COPY = ScanCode.SDL_SCANCODE_COPY | ScanCode.MASK,
        SDLK_PASTE = ScanCode.SDL_SCANCODE_PASTE | ScanCode.MASK,
        SDLK_FIND = ScanCode.SDL_SCANCODE_FIND | ScanCode.MASK,
        SDLK_MUTE = ScanCode.SDL_SCANCODE_MUTE | ScanCode.MASK,
        SDLK_VOLUMEUP = ScanCode.SDL_SCANCODE_VOLUMEUP | ScanCode.MASK,
        SDLK_VOLUMEDOWN = ScanCode.SDL_SCANCODE_VOLUMEDOWN | ScanCode.MASK,
        SDLK_KP_COMMA = ScanCode.SDL_SCANCODE_KP_COMMA | ScanCode.MASK,
        SDLK_KP_EQUALSAS400 =
        ScanCode.SDL_SCANCODE_KP_EQUALSAS400 | ScanCode.MASK,

        SDLK_ALTERASE = ScanCode.SDL_SCANCODE_ALTERASE | ScanCode.MASK,
        SDLK_SYSREQ = ScanCode.SDL_SCANCODE_SYSREQ | ScanCode.MASK,
        SDLK_CANCEL = ScanCode.SDL_SCANCODE_CANCEL | ScanCode.MASK,
        SDLK_CLEAR = ScanCode.SDL_SCANCODE_CLEAR | ScanCode.MASK,
        SDLK_PRIOR = ScanCode.SDL_SCANCODE_PRIOR | ScanCode.MASK,
        SDLK_RETURN2 = ScanCode.SDL_SCANCODE_RETURN2 | ScanCode.MASK,
        SDLK_SEPARATOR = ScanCode.SDL_SCANCODE_SEPARATOR | ScanCode.MASK,
        SDLK_OUT = ScanCode.SDL_SCANCODE_OUT | ScanCode.MASK,
        SDLK_OPER = ScanCode.SDL_SCANCODE_OPER | ScanCode.MASK,
        SDLK_CLEARAGAIN = ScanCode.SDL_SCANCODE_CLEARAGAIN | ScanCode.MASK,
        SDLK_CRSEL = ScanCode.SDL_SCANCODE_CRSEL | ScanCode.MASK,
        SDLK_EXSEL = ScanCode.SDL_SCANCODE_EXSEL | ScanCode.MASK,

        SDLK_KP_00 = ScanCode.SDL_SCANCODE_KP_00 | ScanCode.MASK,
        SDLK_KP_000 = ScanCode.SDL_SCANCODE_KP_000 | ScanCode.MASK,
        SDLK_THOUSANDSSEPARATOR =
        ScanCode.SDL_SCANCODE_THOUSANDSSEPARATOR | ScanCode.MASK,
        SDLK_DECIMALSEPARATOR =
        ScanCode.SDL_SCANCODE_DECIMALSEPARATOR | ScanCode.MASK,
        SDLK_CURRENCYUNIT = ScanCode.SDL_SCANCODE_CURRENCYUNIT | ScanCode.MASK,
        SDLK_CURRENCYSUBUNIT =
        ScanCode.SDL_SCANCODE_CURRENCYSUBUNIT | ScanCode.MASK,
        SDLK_KP_LEFTPAREN = ScanCode.SDL_SCANCODE_KP_LEFTPAREN | ScanCode.MASK,
        SDLK_KP_RIGHTPAREN = ScanCode.SDL_SCANCODE_KP_RIGHTPAREN | ScanCode.MASK,
        SDLK_KP_LEFTBRACE = ScanCode.SDL_SCANCODE_KP_LEFTBRACE | ScanCode.MASK,
        SDLK_KP_RIGHTBRACE = ScanCode.SDL_SCANCODE_KP_RIGHTBRACE | ScanCode.MASK,
        SDLK_KP_TAB = ScanCode.SDL_SCANCODE_KP_TAB | ScanCode.MASK,
        SDLK_KP_BACKSPACE = ScanCode.SDL_SCANCODE_KP_BACKSPACE | ScanCode.MASK,
        SDLK_KP_A = ScanCode.SDL_SCANCODE_KP_A | ScanCode.MASK,
        SDLK_KP_B = ScanCode.SDL_SCANCODE_KP_B | ScanCode.MASK,
        SDLK_KP_C = ScanCode.SDL_SCANCODE_KP_C | ScanCode.MASK,
        SDLK_KP_D = ScanCode.SDL_SCANCODE_KP_D | ScanCode.MASK,
        SDLK_KP_E = ScanCode.SDL_SCANCODE_KP_E | ScanCode.MASK,
        SDLK_KP_F = ScanCode.SDL_SCANCODE_KP_F | ScanCode.MASK,
        SDLK_KP_XOR = ScanCode.SDL_SCANCODE_KP_XOR | ScanCode.MASK,
        SDLK_KP_POWER = ScanCode.SDL_SCANCODE_KP_POWER | ScanCode.MASK,
        SDLK_KP_PERCENT = ScanCode.SDL_SCANCODE_KP_PERCENT | ScanCode.MASK,
        SDLK_KP_LESS = ScanCode.SDL_SCANCODE_KP_LESS | ScanCode.MASK,
        SDLK_KP_GREATER = ScanCode.SDL_SCANCODE_KP_GREATER | ScanCode.MASK,
        SDLK_KP_AMPERSAND = ScanCode.SDL_SCANCODE_KP_AMPERSAND | ScanCode.MASK,
        SDLK_KP_DBLAMPERSAND =
        ScanCode.SDL_SCANCODE_KP_DBLAMPERSAND | ScanCode.MASK,
        SDLK_KP_VERTICALBAR =
        ScanCode.SDL_SCANCODE_KP_VERTICALBAR | ScanCode.MASK,
        SDLK_KP_DBLVERTICALBAR =
        ScanCode.SDL_SCANCODE_KP_DBLVERTICALBAR | ScanCode.MASK,
        SDLK_KP_COLON = ScanCode.SDL_SCANCODE_KP_COLON | ScanCode.MASK,
        SDLK_KP_HASH = ScanCode.SDL_SCANCODE_KP_HASH | ScanCode.MASK,
        SDLK_KP_SPACE = ScanCode.SDL_SCANCODE_KP_SPACE | ScanCode.MASK,
        SDLK_KP_AT = ScanCode.SDL_SCANCODE_KP_AT | ScanCode.MASK,
        SDLK_KP_EXCLAM = ScanCode.SDL_SCANCODE_KP_EXCLAM | ScanCode.MASK,
        SDLK_KP_MEMSTORE = ScanCode.SDL_SCANCODE_KP_MEMSTORE | ScanCode.MASK,
        SDLK_KP_MEMRECALL = ScanCode.SDL_SCANCODE_KP_MEMRECALL | ScanCode.MASK,
        SDLK_KP_MEMCLEAR = ScanCode.SDL_SCANCODE_KP_MEMCLEAR | ScanCode.MASK,
        SDLK_KP_MEMADD = ScanCode.SDL_SCANCODE_KP_MEMADD | ScanCode.MASK,
        SDLK_KP_MEMSUBTRACT =
        ScanCode.SDL_SCANCODE_KP_MEMSUBTRACT | ScanCode.MASK,
        SDLK_KP_MEMMULTIPLY =
        ScanCode.SDL_SCANCODE_KP_MEMMULTIPLY | ScanCode.MASK,
        SDLK_KP_MEMDIVIDE = ScanCode.SDL_SCANCODE_KP_MEMDIVIDE | ScanCode.MASK,
        SDLK_KP_PLUSMINUS = ScanCode.SDL_SCANCODE_KP_PLUSMINUS | ScanCode.MASK,
        SDLK_KP_CLEAR = ScanCode.SDL_SCANCODE_KP_CLEAR | ScanCode.MASK,
        SDLK_KP_CLEARENTRY = ScanCode.SDL_SCANCODE_KP_CLEARENTRY | ScanCode.MASK,
        SDLK_KP_BINARY = ScanCode.SDL_SCANCODE_KP_BINARY | ScanCode.MASK,
        SDLK_KP_OCTAL = ScanCode.SDL_SCANCODE_KP_OCTAL | ScanCode.MASK,
        SDLK_KP_DECIMAL = ScanCode.SDL_SCANCODE_KP_DECIMAL | ScanCode.MASK,
        SDLK_KP_HEXADECIMAL =
        ScanCode.SDL_SCANCODE_KP_HEXADECIMAL | ScanCode.MASK,

        SDLK_LCTRL = ScanCode.SDL_SCANCODE_LCTRL | ScanCode.MASK,
        SDLK_LSHIFT = ScanCode.SDL_SCANCODE_LSHIFT | ScanCode.MASK,
        SDLK_LALT = ScanCode.SDL_SCANCODE_LALT | ScanCode.MASK,
        SDLK_LGUI = ScanCode.SDL_SCANCODE_LGUI | ScanCode.MASK,
        SDLK_RCTRL = ScanCode.SDL_SCANCODE_RCTRL | ScanCode.MASK,
        SDLK_RSHIFT = ScanCode.SDL_SCANCODE_RSHIFT | ScanCode.MASK,
        SDLK_RALT = ScanCode.SDL_SCANCODE_RALT | ScanCode.MASK,
        SDLK_RGUI = ScanCode.SDL_SCANCODE_RGUI | ScanCode.MASK,

        SDLK_MODE = ScanCode.SDL_SCANCODE_MODE | ScanCode.MASK,

        SDLK_AUDIONEXT = ScanCode.SDL_SCANCODE_AUDIONEXT | ScanCode.MASK,
        SDLK_AUDIOPREV = ScanCode.SDL_SCANCODE_AUDIOPREV | ScanCode.MASK,
        SDLK_AUDIOSTOP = ScanCode.SDL_SCANCODE_AUDIOSTOP | ScanCode.MASK,
        SDLK_AUDIOPLAY = ScanCode.SDL_SCANCODE_AUDIOPLAY | ScanCode.MASK,
        SDLK_AUDIOMUTE = ScanCode.SDL_SCANCODE_AUDIOMUTE | ScanCode.MASK,
        SDLK_MEDIASELECT = ScanCode.SDL_SCANCODE_MEDIASELECT | ScanCode.MASK,
        SDLK_WWW = ScanCode.SDL_SCANCODE_WWW | ScanCode.MASK,
        SDLK_MAIL = ScanCode.SDL_SCANCODE_MAIL | ScanCode.MASK,
        SDLK_CALCULATOR = ScanCode.SDL_SCANCODE_CALCULATOR | ScanCode.MASK,
        SDLK_COMPUTER = ScanCode.SDL_SCANCODE_COMPUTER | ScanCode.MASK,
        SDLK_AC_SEARCH = ScanCode.SDL_SCANCODE_AC_SEARCH | ScanCode.MASK,
        SDLK_AC_HOME = ScanCode.SDL_SCANCODE_AC_HOME | ScanCode.MASK,
        SDLK_AC_BACK = ScanCode.SDL_SCANCODE_AC_BACK | ScanCode.MASK,
        SDLK_AC_FORWARD = ScanCode.SDL_SCANCODE_AC_FORWARD | ScanCode.MASK,
        SDLK_AC_STOP = ScanCode.SDL_SCANCODE_AC_STOP | ScanCode.MASK,
        SDLK_AC_REFRESH = ScanCode.SDL_SCANCODE_AC_REFRESH | ScanCode.MASK,
        SDLK_AC_BOOKMARKS = ScanCode.SDL_SCANCODE_AC_BOOKMARKS | ScanCode.MASK,

        SDLK_BRIGHTNESSDOWN =
        ScanCode.SDL_SCANCODE_BRIGHTNESSDOWN | ScanCode.MASK,
        SDLK_BRIGHTNESSUP = ScanCode.SDL_SCANCODE_BRIGHTNESSUP | ScanCode.MASK,
        SDLK_DISPLAYSWITCH = ScanCode.SDL_SCANCODE_DISPLAYSWITCH | ScanCode.MASK,
        SDLK_KBDILLUMTOGGLE =
        ScanCode.SDL_SCANCODE_KBDILLUMTOGGLE | ScanCode.MASK,
        SDLK_KBDILLUMDOWN = ScanCode.SDL_SCANCODE_KBDILLUMDOWN | ScanCode.MASK,
        SDLK_KBDILLUMUP = ScanCode.SDL_SCANCODE_KBDILLUMUP | ScanCode.MASK,
        SDLK_EJECT = ScanCode.SDL_SCANCODE_EJECT | ScanCode.MASK,
        SDLK_SLEEP = ScanCode.SDL_SCANCODE_SLEEP | ScanCode.MASK
    }
}
